# Non Graded Challenge 4 - Linear Algebra 2

In [27]:
import numpy as np

---

Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

In [28]:
T1 = np.array([[23, 50],
               [7, 12]])
T2 = np.array([[57, 67],
               [99, 43]])
T3 = np.array([[75, 21],
               [57, 12]])
T4 = np.array([[87, 26],
               [18, 84]])
T = np.array([[T1, T2],
              [T3, T4]])
T

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [29]:
T.shape

(2, 2, 2, 2)

---

Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

In [30]:
A = np.array([[23, 50, 19],
              [7, 12, 109],
              [57, 67, 98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [31]:
B = np.array([[17], [22], [19]])
B

array([[17],
       [22],
       [19]])

In [32]:
A @ B

array([[1852],
       [2454],
       [4305]])

---

Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$


In [37]:
A 

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

Transpose A

In [34]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

Determinan A

In [35]:
np.linalg.det(A)

131344.0000000002

Inverse A

In [36]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])